### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by m-ar-c** [nesivmi/ulauncher-iplik#8]
Hello,

I can't find licence information anywhere. Please add a (hopefully, Free as in freedom) licence file :)

**Comment by manahter** [comment]
Which license type would you like?

![resim](https://user-images.githubusercontent.com/73780835/147681904-e2ea548d-97ad-498a-bc94-414cfdf43127.png)

**Comment by m-ar-c** [comment]
GNU General Public Licence v3.0 would do 🙂

**Comment by manahter** [comment]
job ok ;-)
